version: "1"
services:
  xm-app-service:
    build: .
    container_name: xm-app
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    depends_on:
      - mysqldb
    restart: on-failure
  mysqldb:
    container_name: xm-app-db
    image: mysql
    restart: on-failure
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: xm_db
      MYSQL_ROOT_PASSWORD: root